// Code generated by "stringer -type=ItemState"; DO NOT EDIT.

package list

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ItemNotSelected-1]
	_ = x[ItemSelected-2]
	_ = x[ItemListOpen-3]
	_ = x[ItemListClosed-4]
}

const _ItemState_name = "ItemNotSelectedItemSelectedItemListOpenItemListClosed"

var _ItemState_index = [...]uint8{0, 15, 27, 39, 53}

func (i ItemState) String() string {
	i -= 1
	if i < 0 || i >= ItemState(len(_ItemState_index)-1) {
		return "ItemState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ItemState_name[_ItemState_index[i]:_ItemState_index[i+1]]
}
