package list

import (
	"github.com/charmbracelet/bubbles/list"
	"github.com/charmbracelet/lipgloss"
	"github.com/ohzqq/teacozy/color"
)

const (
	bullet   = "•"
	ellipsis = "…"
)

// Styles contains style definitions for this list component. By default, these
// values are generated by DefaultStyles.
type Styles struct {
	list.Styles
}

// DefaultStyles returns a set of default style definitions for this list
// component.
func DefaultStyles() (s list.Styles) {
	verySubduedColor := color.DarkGrey
	subduedColor := color.Grey

	s.TitleBar = lipgloss.NewStyle().Padding(0, 0, 0, 2)

	s.Title = lipgloss.NewStyle().
		Foreground(color.Purple).
		Padding(0, 1)

	s.Spinner = lipgloss.NewStyle().
		Foreground(color.Red)

	s.FilterPrompt = lipgloss.NewStyle().
		Foreground(color.Yellow)

	s.FilterCursor = lipgloss.NewStyle().
		Foreground(color.Pink)

	s.DefaultFilterCharacterMatch = lipgloss.NewStyle().Underline(true)

	s.StatusBar = lipgloss.NewStyle().
		Foreground(color.Grey).
		Padding(0, 0, 0, 2)

	s.StatusEmpty = lipgloss.NewStyle().
		Foreground(subduedColor)

	s.StatusBarActiveFilter = lipgloss.NewStyle().
		Foreground(color.White)

	s.StatusBarFilterCount = lipgloss.NewStyle().
		Foreground(verySubduedColor)

	s.NoItems = lipgloss.NewStyle().
		Foreground(color.Grey)

	s.ArabicPagination = lipgloss.NewStyle().
		Foreground(subduedColor)

	s.PaginationStyle = lipgloss.NewStyle().PaddingLeft(2) //nolint:gomnd

	s.HelpStyle = lipgloss.NewStyle().Padding(0, 0, 0, 2)

	s.ActivePaginationDot = lipgloss.NewStyle().
		Foreground(color.Cyan).
		SetString(bullet)

	s.InactivePaginationDot = lipgloss.NewStyle().
		Foreground(verySubduedColor).
		SetString(bullet)

	s.DividerDot = lipgloss.NewStyle().
		Foreground(verySubduedColor).
		SetString(" " + bullet + " ")

	return s
}

// DefaultItemStyles defines styling for a default list item.
// See DefaultItemView for when these come into play.
type DefaultItemStyles struct {
	list.DefaultItemStyles
	Prefix  lipgloss.Style
	Toggled lipgloss.Style
}

// NewDefaultItemStyles returns style definitions for a default item. See
// DefaultItemView for when these come into play.
func NewDefaultItemStyles() (s DefaultItemStyles) {
	s.NormalTitle = lipgloss.NewStyle().
		Foreground(color.Fg).
		Padding(0, 0, 0, 1)

	s.NormalDesc = s.NormalTitle.Copy().
		Foreground(color.White)

	s.SelectedTitle = lipgloss.NewStyle().
		Foreground(color.Green).
		Padding(0, 0, 0, 1)

	s.Prefix = s.SelectedTitle.Copy().Padding(0)

	s.SelectedDesc = s.SelectedTitle.Copy().
		Foreground(color.Purple)

	s.DimmedTitle = lipgloss.NewStyle().
		Foreground(color.DarkGrey).
		Padding(0, 0, 0, 1)

	s.DimmedDesc = s.DimmedTitle.Copy().
		Foreground(color.Green)

	s.FilterMatch = lipgloss.NewStyle().Underline(true)

	s.Toggled = lipgloss.NewStyle().
		Foreground(color.Grey)

	return s
}
