// Code generated by gomplate -f _gen/color.tmpl -o gen_color.go -c .=_gen/color.toml; Do Not Edit
package color

import "github.com/charmbracelet/lipgloss"

var color = Color{
	Bg: lipgloss.Color("#262626"),
	Black: lipgloss.Color("#262626"),
	Blue: lipgloss.Color("#5FAFFF"),
	Cyan: lipgloss.Color("#AFFFFF"),
	Fg: lipgloss.Color("#FFBF00"),
	Green: lipgloss.Color("#AFFFAF"),
	Grey: lipgloss.Color("#626262"),
	Pink: lipgloss.Color("#FFAFFF"),
	Purple: lipgloss.Color("#AF87FF"),
	Red: lipgloss.Color("#FF5F5F"),
	White: lipgloss.Color("#FFFFFF"),
	Yellow: lipgloss.Color("#FFFF87"),
}

func SetColors(c map[string]string) {
	for color, val := range c {
		switch color {
		
		case "bg", "Bg":
			SetBg(val)
		
		case "black", "Black":
			SetBlack(val)
		
		case "blue", "Blue":
			SetBlue(val)
		
		case "cyan", "Cyan":
			SetCyan(val)
		
		case "fg", "Fg":
			SetFg(val)
		
		case "green", "Green":
			SetGreen(val)
		
		case "grey", "Grey":
			SetGrey(val)
		
		case "pink", "Pink":
			SetPink(val)
		
		case "purple", "Purple":
			SetPurple(val)
		
		case "red", "Red":
			SetRed(val)
		
		case "white", "White":
			SetWhite(val)
		
		case "yellow", "Yellow":
			SetYellow(val)
		
		}
	}
}


func Bg() lipgloss.Color {
	return color.Bg
}

func SetBg(c string) {
	color.Bg = lipgloss.Color("#262626")
}

func Black() lipgloss.Color {
	return color.Black
}

func SetBlack(c string) {
	color.Black = lipgloss.Color("#262626")
}

func Blue() lipgloss.Color {
	return color.Blue
}

func SetBlue(c string) {
	color.Blue = lipgloss.Color("#5FAFFF")
}

func Cyan() lipgloss.Color {
	return color.Cyan
}

func SetCyan(c string) {
	color.Cyan = lipgloss.Color("#AFFFFF")
}

func Fg() lipgloss.Color {
	return color.Fg
}

func SetFg(c string) {
	color.Fg = lipgloss.Color("#FFBF00")
}

func Green() lipgloss.Color {
	return color.Green
}

func SetGreen(c string) {
	color.Green = lipgloss.Color("#AFFFAF")
}

func Grey() lipgloss.Color {
	return color.Grey
}

func SetGrey(c string) {
	color.Grey = lipgloss.Color("#626262")
}

func Pink() lipgloss.Color {
	return color.Pink
}

func SetPink(c string) {
	color.Pink = lipgloss.Color("#FFAFFF")
}

func Purple() lipgloss.Color {
	return color.Purple
}

func SetPurple(c string) {
	color.Purple = lipgloss.Color("#AF87FF")
}

func Red() lipgloss.Color {
	return color.Red
}

func SetRed(c string) {
	color.Red = lipgloss.Color("#FF5F5F")
}

func White() lipgloss.Color {
	return color.White
}

func SetWhite(c string) {
	color.White = lipgloss.Color("#FFFFFF")
}

func Yellow() lipgloss.Color {
	return color.Yellow
}

func SetYellow(c string) {
	color.Yellow = lipgloss.Color("#FFFF87")
}

